Aborting with 403 when a user have no orgs
georchestra/ckanext-georchestra pull request #17
Opened 2019-07-02 07:51 UTC by RemiDesgrange

2019-07-02 07:58 UTC, tonio approved these changes

2019-07-02 07:58 UTC, tonio commented on ckanext/georchestra/utils/organizations.py
> +        abort(403)
Looks like passing a message as second argument is possible, wouldn't it be useful?

2019-07-02 09:28 UTC, jeanpommier commented
Finally, we don't accept users with no org ? It might be worth looking at the code then, I'm pretty sure we can do some clean up (François asked me to support users with no orgs, I remember writing specific code for this case)

2019-07-03 08:02 UTC, RemiDesgrange commented
hum :thinking: @jeanpommier do you want me to have a look ?

2019-07-04 07:25 UTC, fvanderbiest requested changes
Users with no Org should be able to browse public CKAN pages without having a 403 ...

2019-07-04 13:08 UTC, RemiDesgrange commented on ckanext/georchestra/utils/organizations.py
> +    if org_id == '':
the interesting part is here :-)

2019-07-06 06:10 UTC, fvanderbiest commented
Can you tell us about the consequences of setting `org_id = 'empty_org'` here ?

2019-07-23 07:28 UTC, RemiDesgrange commented
It create an org called `empty_org` in ckan. If the `empty_org` exist, it put the user in this org.

2019-08-02 11:00 UTC, fvanderbiest commented on ckanext/georchestra/utils/organizations.py
> +from ckan.lib.base import abort
useless import ?

2019-08-02 11:04 UTC, fvanderbiest commented
I don't really like this fix, it's a hacky workaround.
Instead, can we prevent the `organization_set_member_or_create` method from being called when the user has no Org ? cc @jeanpommier

2019-08-21 10:42 UTC, closed without merging